'use client'

import { ResetCountdown } from '@/components/community-leaderboard'
import { Content } from '@/components/content'
import { Leaderboard } from '@anonworld/react'
import { LeaderboardSelector } from '@anonworld/react'
import { Text, View } from '@anonworld/ui'
import { XStack } from '@anonworld/ui'
import { useState } from 'react'

export default function Page() {
  const [selected, setSelected] = useState<'week' | 'last-week' | 'all-time'>('week')

  return (
    <Content>
      <XStack ai="center" jc="space-between" $xs={{ px: '$2' }}>
        <XStack ai="center" jc="center" gap="$2">
          <Text fow="600" fos="$4">
            Leaderboard
          </Text>
          <View bg="$green9" px="$1.5" py="$1" br="$2">
            <Text fos="$1" fow="600" color="$green12">
              BETA
            </Text>
          </View>
        </XStack>
        <LeaderboardSelector selected={selected} setSelected={setSelected} />
      </XStack>
      <View
        bg="$green1"
        p="$3"
        br="$4"
        bc="$green8"
        bw="$0.5"
        gap="$3"
        $xs={{ mx: '$3' }}
      >
        <Text fos="$2" fow="400" color="$green12">
          Leaderboard scores reflect Farcaster engagement generated by the poster, with
          higher weight given to interactions from users with more distribution. Each
          community maintains its own separate leaderboard, updated hourly, with weekly
          resets every Wednesday at 4pm UTC.
        </Text>
        <Text fos="$2" fow="400" color="$green12">
          Starting January 15th, top posters in communities with anon.world-launched
          tokens will earn rewards. Rewards are funded by trading fees generated from the
          community token and will be anonymously claimable through Veil. The first
          distribution will be on January 22nd. Full details coming soon.
        </Text>
        <Text fos="$2" fow="400" color="$green12">
          Leaderboards and rewards are an experimental feature and subject to change.
        </Text>
        <XStack ai="center" jc="space-between">
          <View />
          <ResetCountdown />
        </XStack>
      </View>
      <Leaderboard timeframe={selected} />
    </Content>
  )
}
